package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"
	"strconv"

	"github.com/bunhojun/golang-next-practice/api/graph/model"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	// Parse user ID
	userID, err := strconv.Atoi(input.UserID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}
	// Insert new todo
	var todoID int
	if err := r.DB.QueryRowContext(ctx,
		"INSERT INTO todos (text, done, user_id) VALUES ($1, false, $2) RETURNING id",
		input.Text, userID,
	).Scan(&todoID); err != nil {
		return nil, fmt.Errorf("failed to create todo: %w", err)
	}
	// Query created todo with user info
	var id, uid int
	var text, name string
	var done bool
	if err := r.DB.QueryRowContext(ctx,
		`SELECT t.id, t.text, t.done, u.id, u.name
		 FROM todos t JOIN users u ON t.user_id = u.id WHERE t.id = $1`, todoID,
	).Scan(&id, &text, &done, &uid, &name); err != nil {
		return nil, fmt.Errorf("failed to fetch new todo: %w", err)
	}
	return &model.Todo{
		ID:   strconv.Itoa(id),
		Text: text,
		Done: done,
		User: &model.User{ID: strconv.Itoa(uid), Name: name},
	}, nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, input model.UpdateTodo) (*model.Todo, error) {
	_, err := r.DB.ExecContext(ctx, "UPDATE todos SET text = $1, done = $2 WHERE id = $3", input.Text, input.Done, id)
	if err != nil {
		return nil, fmt.Errorf("failed to update todo: %w", err)
	}
	return &model.Todo{
		ID:   id,
		Text: *input.Text,
		Done: *input.Done,
	}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	rows, err := r.DB.QueryContext(ctx,
		`SELECT t.id, t.text, t.done, u.id, u.name
		 FROM todos t JOIN users u ON t.user_id = u.id`,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to query todos: %w", err)
	}
	defer rows.Close()
	var todos []*model.Todo
	for rows.Next() {
		var id, uid int
		var text, name string
		var done bool
		if err := rows.Scan(&id, &text, &done, &uid, &name); err != nil {
			return nil, fmt.Errorf("failed to scan todo: %w", err)
		}
		todos = append(todos, &model.Todo{
			ID:   strconv.Itoa(id),
			Text: text,
			Done: done,
			User: &model.User{ID: strconv.Itoa(uid), Name: name},
		})
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("rows error: %w", err)
	}
	return todos, nil
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, id string) (*model.Todo, error) {
	var todoID, userID int
	var text, name string
	var done bool

	err := r.DB.QueryRowContext(ctx,
		`SELECT t.id, t.text, t.done, u.id, u.name
         FROM todos t JOIN users u ON t.user_id = u.id 
         WHERE t.id = $1`,
		id,
	).Scan(&todoID, &text, &done, &userID, &name)

	if err != nil {
		return nil, fmt.Errorf("failed to fetch todo: %w", err)
	}

	return &model.Todo{
		ID:   strconv.Itoa(todoID),
		Text: text,
		Done: done,
		User: &model.User{
			ID:   strconv.Itoa(userID),
			Name: name,
		},
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	rows, _ := r.DB.QueryContext(ctx, "SELECT id,name FROM users")
	defer rows.Close()
	var users []*model.User
	for rows.Next() {
		var id int
		var name string
		if err := rows.Scan(&id, &name); err != nil {
			return nil, fmt.Errorf("failed to scan user: %w", err)
		}
		users = append(users, &model.User{ID: strconv.Itoa(id), Name: name})
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("rows error: %w", err)
	}
	return users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	var userID int
	var name string
	var todos []*model.Todo
	err := r.DB.QueryRowContext(ctx,
		`SELECT id, name FROM users WHERE id = $1`,
		id,
	).Scan(&userID, &name)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch user: %w", err)
	}
	rows, err := r.DB.QueryContext(ctx,
		`SELECT t.id, t.text, t.done FROM todos t JOIN users u ON t.user_id = u.id WHERE u.id = $1`,
		userID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch todos: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var id int
		var text string
		var done bool
		if err := rows.Scan(&id, &text, &done); err != nil {
			return nil, fmt.Errorf("failed to scan todo: %w", err)
		}
		todos = append(todos, &model.Todo{ID: strconv.Itoa(id), Text: text, Done: done})
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("rows error: %w", err)
	}
	return &model.User{ID: strconv.Itoa(userID), Name: name, Todos: todos}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
